### Импорты

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, Normalizer
from sklearn.cluster import KMeans
from sklearn.metrics import davies_bouldin_score
import pickle
import pandas as pd

Получаю данные из базы данных

In [10]:
df = pd.read_sql_table(table_name="track_analysis", con="postgresql://arthur:146a@localhost:5430/db_arthur")

In [11]:
df

,track_id,track_time,latitude,longitude,altitude,region,steps,terrain_type,key_objects_str,temperature
0,0,2018-08-26,55.633018,109.342398,524.87,городской округ Северобайкальск,0.000000,grass,River: Муякан; Settlement: Северобайкальск (town),17.500000
1,0,2018-08-26,55.633006,109.342371,527.28,городской округ Северобайкальск,2.883445,grass,River: Муякан; Settlement: Северобайкальск (town),17.500489
2,0,2018-08-26,55.633463,109.342683,508.52,городской округ Северобайкальск,72.723925,grass,River: Муякан; Settlement: Северобайкальск (town),17.500979
3,0,2018-08-26,55.633469,109.342643,502.76,городской округ Северобайкальск,3.475120,grass,River: Муякан; Settlement: Северобайкальск (town),17.501468
4,0,2018-08-26,55.633475,109.342641,500.35,городской округ Северобайкальск,0.906378,grass,River: Муякан; Settlement: Северобайкальск (town),17.501957
...,...,...,...,...,...,...,...,...,...,...
46240,2,2009-08-27,61.852395,33.226315,103.97,Лодейнопольский район,19.765705,NaN,NaN,15.403873
46241,2,2009-08-27,61.852410,33.226316,105.74,Лодейнопольский район,2.229969,NaN,NaN,15.402905
46242,2,2009-08-27,61.852416,33.226325,104.03,Лодейнопольский район,1.092725,NaN,NaN,15.401936
46243,2,2009-08-27,61.852449,33.226341,105.22,Лодейнопольский район,5.030503,NaN,NaN,15.400968
46244,2,2009-08-27,61.852452,33.226340,103.94,Лодейнопольский район,0.451267,NaN,NaN,15.400000

Создаю две новые колонки: источники воды и горы

In [15]:
df["water_source"] = df["key_objects_str"].apply(
    lambda x: 1 if pd.notna(x) and isinstance(x, str) and 'river' in x.lower() else 0
)
df["mountain"] = df["key_objects_str"].apply(
    lambda x: 1 if pd.notna(x) and isinstance(x, str) and 'mountain' in x.lower() else 0
)

In [16]:
df

,track_id,track_time,latitude,longitude,altitude,region,steps,terrain_type,key_objects_str,temperature,water_source,mountain
0,0,2018-08-26,55.633018,109.342398,524.87,городской округ Северобайкальск,0.000000,grass,River: Муякан; Settlement: Северобайкальск (town),17.500000,1,0
1,0,2018-08-26,55.633006,109.342371,527.28,городской округ Северобайкальск,2.883445,grass,River: Муякан; Settlement: Северобайкальск (town),17.500489,1,0
2,0,2018-08-26,55.633463,109.342683,508.52,городской округ Северобайкальск,72.723925,grass,River: Муякан; Settlement: Северобайкальск (town),17.500979,1,0
3,0,2018-08-26,55.633469,109.342643,502.76,городской округ Северобайкальск,3.475120,grass,River: Муякан; Settlement: Северобайкальск (town),17.501468,1,0
4,0,2018-08-26,55.633475,109.342641,500.35,городской округ Северобайкальск,0.906378,grass,River: Муякан; Settlement: Северобайкальск (town),17.501957,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
46240,2,2009-08-27,61.852395,33.226315,103.97,Лодейнопольский район,19.765705,NaN,NaN,15.403873,0,0
46241,2,2009-08-27,61.852410,33.226316,105.74,Лодейнопольский район,2.229969,NaN,NaN,15.402905,0,0
46242,2,2009-08-27,61.852416,33.226325,104.03,Лодейнопольский район,1.092725,NaN,NaN,15.401936,0,0
46243,2,2009-08-27,61.852449,33.226341,105.22,Лодейнопольский район,5.030503,NaN,NaN,15.400968,0,0
46244,2,2009-08-27,61.852452,33.226340,103.94,Лодейнопольский район,0.451267,NaN,NaN,15.400000,0,0

In [17]:
df = df.rename(str, axis=1)

In [19]:
malt = df["altitude"].max()
msf = df["steps"].max()

In [20]:
df["water_danger"] = df.apply(lambda x: (
	3 < x["temperature"] < 10) * 3 + 
	(x["temperature"] >= 10) + x["water_source"] * 4 + (x["terrain_type"] == 3) * 
	6 + round((malt - x["altitude"])/malt, 2), axis=1)

In [21]:
df["fire_danger"] = df.apply(lambda x: (1-x["water_source"])*2 - (x["terrain_type"] == 3) * 4 + (x["terrain_type"] == 0) * 2 + (x["terrain_type"] == 1) * 2 + round(x["temperature"]/10, 2), axis=1)

In [25]:
mealt = (df["altitude"].max() - df["altitude"].min()) / 2
msf = df["steps"].max()

In [27]:
df["difficult"] = df.apply(lambda x: (x["terrain_type"] == 0) * 2 + (x["mountain"]) * 4 + round(abs(mealt-x["altitude"])/mealt*2, 2) + (x["mountain"]) * 4 + round((msf-x["steps"])/msf, 2), axis=1)

In [28]:
df.head()

,track_id,track_time,latitude,longitude,altitude,region,steps,terrain_type,key_objects_str,temperature,water_source,mountain,water_danger,fire_danger,difficult
0,0,2018-08-26,55.633018,109.342398,524.87,городской округ Северобайкальск,0.000000,grass,River: Муякан; Settlement: Северобайкальск (town),17.500000,1,0,5.54,1.75,1.18
1,0,2018-08-26,55.633006,109.342371,527.28,городской округ Северобайкальск,2.883445,grass,River: Муякан; Settlement: Северобайкальск (town),17.500489,1,0,5.54,1.75,1.17
2,0,2018-08-26,55.633463,109.342683,508.52,городской округ Северобайкальск,72.723925,grass,River: Муякан; Settlement: Северобайкальск (town),17.500979,1,0,5.56,1.75,1.24
3,0,2018-08-26,55.633469,109.342643,502.76,городской округ Северобайкальск,3.475120,grass,River: Муякан; Settlement: Северобайкальск (town),17.501468,1,0,5.56,1.75,1.26
4,0,2018-08-26,55.633475,109.342641,500.35,городской округ Северобайкальск,0.906378,grass,River: Муякан; Settlement: Северобайкальск (town),17.501957,1,0,5.57,1.75,1.27

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46245 entries, 0 to 46244
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   track_id         46245 non-null  int64
 1   track_time       46245 non-null  str
 2   latitude         46245 non-null  float64
 3   longitude        46245 non-null  float64
 4   altitude         46245 non-null  float64
 5   region           46245 non-null  str
 6   steps            46245 non-null  float64
 7   terrain_type     37565 non-null  str
 8   key_objects_str  37565 non-null  str
 9   temperature      46245 non-null  float64
 10  water_source     46245 non-null  int64
 11  mountain         46245 non-null  int64
 12  water_danger     46245 non-null  float64
 13  fire_danger      46245 non-null  float64
 14  difficult        46245 non-null  float64
dtypes: float64(8), int64(3), str(4)
memory usage: 10.8 MB

In [30]:
with open("encodings.pkl", "rb") as f:
    encodings = pickle.load(f)

FileNotFoundError: [Errno 2] No such file or directory: 'encodings.pkl'

In [ ]:
def pca2(df):
    # Масштабирую данные
    ddf = StandardScaler().fit_transform(df)

    # Нормализирую данные
    ddt = Normalizer().fit_transform(ddf)
    
    # Уменьшаем размерность при помощи метода главных компонент
    pca = PCA(n_components=2).fit(ddt)
    pca_2d = pca.transform(ddt)
    return pca_2d

def elbow(pca_2d):
    sse = []
    # Смотрю, какая сумма квадратов расстояния для разного кол-ва класстеров
    for k in range(1, 11):
        kmeans = KMeans(n_clusters=k, random_state=42)
        kmeans.fit(pca_2d)
        sse.append(kmeans.inertia_)
    # Изображаю график метода Локтя
    plt.plot(range(1, 11), sse, marker='o')
    plt.title('Метод „Локтя“')
    plt.xlabel('Количество кластеров')
    plt.ylabel('Сумма квадратов расстояний')
    plt.show()

list_of_color = ["red", "blue", "green", "orange"]

def KMN(df, pca_2d, n_clusters):
    # Обучаю и предсказываю кластеры по уже известному их кол-ву
    km = KMeans(n_clusters=n_clusters, random_state=0, init = 'k-means++')
    all_pred = km.fit_predict(pca_2d)
    # Визуализирую кластеры
    for k in range(n_clusters):
        plt.scatter(pca_2d[all_pred==k].T[0] , pca_2d[all_pred==k].T[1], color=list_of_color[k])
        
    plt.title(f'Кластеризация KMeans')
    plt.show()

    # Описываю характеристики по каждому столбцу каждого кластера
    for i in range(n_clusters):
        print(f"{i+1} кластер. Кол-во: {km.labels_[km.labels_==i].size}\n")
        print(f"Цвет: {list_of_color[i]}\n")
        for j in df.columns:
            if j in ["bridge", "building", "mountain_peak", "none", "road", "water_source"]:
                print(f"Кол-во {j}: {df[j][km.labels_==i].sum()}")
                continue
            if j in ["region", "terrain_type"]:
                dmode = map(str, df[j][km.labels_==i].value_counts().reset_index()[j][:2])
                print(f"Преобладает {j}: {' и '.join(dmode)}")
                continue
            print(f"Среднее {j}: {df[j][km.labels_==i].mean():.3f}")
        print()
    # Применяю метрику оценки
    dbs = davies_bouldin_score(pca_2d, km.labels_) 
    print(f"Метрика кластеризации (индекс Дэвиса-Булдина): {dbs}")

### Опасная кластеризация

In [ ]:
df_for_danger = df.drop(["track_point_id", "day", "time", "longitude", "latitude", "track_id", "none", "road", "building", "bridge", "difficult"], axis=1)

In [ ]:
danger_df = pca2(df_for_danger)

,analysis_date,region,latitude,longitude,altitude,step_frequency,temperature,terrain_type,key_objects
0,2025-11-18 07:02:44.239,городской округ Геленджик,44.64188,38.002640,120.534016,231.388217,16.274265,NaN,NaN
1,2025-11-18 07:02:44.239,городской округ Геленджик,44.64188,38.002642,120.538518,231.388217,16.300000,NaN,NaN
2,2025-11-18 07:02:44.239,городской округ Геленджик,44.64335,38.003930,143.773920,231.388217,16.222794,NaN,NaN
3,2025-11-18 07:02:44.239,городской округ Геленджик,44.64382,38.004530,150.808992,231.388217,16.197059,NaN,NaN
4,2025-11-18 07:02:44.239,городской округ Геленджик,44.64410,38.005220,158.462400,231.388217,16.171324,NaN,NaN
...,...,...,...,...,...,...,...,...,...
30942,2006-11-26 16:46:24.000,городской округ Новороссийск,44.73628,37.772490,0.610000,596.515925,12.082266,NaN,NaN
30943,2006-11-26 16:52:06.000,городской округ Новороссийск,44.73633,37.771890,43.920000,596.515925,12.086700,NaN,NaN
30944,2006-11-26 17:00:39.000,городской округ Новороссийск,44.73614,37.773240,5.420000,596.515925,12.091133,NaN,NaN
30945,2006-11-26 17:06:20.000,городской округ Новороссийск,44.73626,37.771970,5.420000,596.515925,12.095567,NaN,NaN
30946,2006-11-26 17:09:46.000,городской округ Новороссийск,44.73624,37.771920,-0.330000,596.515925,12.100000,NaN,NaN

### Сложная кластеризация

In [ ]:
df_for_difficult = df.drop(["track_point_id", "day",  "longitude", "latitude", "track_id", "none", "road", "building", "bridge", "fire_danger", "water_danger", "region", "water_source", "danger_level"], axis=1)

In [ ]:
difficult_df = pca2(df_for_difficult)

In [ ]:
elbow(difficult_df)

In [ ]:
clusters_d = KMN(df_for_difficult, difficult_df, n_clusters=4)

Первый кластер - Самый легко эвакуируемый. Сложность = 1

Второй кластер - Тоже легко эвакуируемый, но есть леса. Сложность = 2

Третий кластер - Вероятно сложность возникает из-за окружения пиками. Сложность = 4

Четвёртый кластер - Находится повыше предыдущего. Это в основном луга. Сложность = 3

In [ ]:
transform_d = {0:1, 1:2, 2:4, 3:3}

In [ ]:
df["difficult_level"] = list(map(lambda x: transform_d[x], clusters_d))

In [ ]:
plt.figure(figsize=(15,10))
sns.heatmap(df.corr(), annot=True)
plt.show()

In [ ]:
df.drop(["water_danger", "fire_danger", "difficult"], axis=1, inplace=True)

In [ ]:
df.to_sql("better_data", conn, if_exists="replace")