Агент должен реализовывать функции анализа трендов активности по регионам и сезонам. 

среднюю частоту шагов по трекам в разные сезоны
зависимость температуры от времени суток
влияние типа местности (лес, город, горы) на активность туристов
взаимосвязь высоты маршрута с частотой шагов

Агент должен определять наиболее популярные маршруты в разные периоды года и визуализировать данные с помощью графиков зависимости частоты шагов от температуры и высоты, диаграмм распределения активности по регионам и интерактивных карт с возможностью фильтрации по регионам и времени суток

### Импорты

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, Normalizer
from sklearn.cluster import KMeans
from sklearn.metrics import davies_bouldin_score
import pickle
import pandas as pd

Получаю данные из базы данных

In [2]:
df = pd.read_sql_table(table_name="track_analysis", con="postgresql://arthur:146a@localhost:5430/db_arthur").drop(["id"], axis=1)

In [6]:
df

,track_id,analysis_date,region,latitude,longitude,altitude,step_frequency,temperature,terrain_type,key_objects,created_at
0,track0.gpx,2025-11-17,городской округ Геленджик,44.589199,38.400221,187.926320,NaN,NaN,NaN,NaN,2026-02-06 10:37:47.684766
1,track0.gpx,2025-11-17,городской округ Геленджик,44.589160,38.400190,188.159584,NaN,NaN,NaN,NaN,2026-02-06 10:37:47.684766
2,track0.gpx,2025-11-17,городской округ Геленджик,44.589230,38.400040,188.616480,NaN,NaN,NaN,NaN,2026-02-06 10:37:47.684766
3,track0.gpx,2025-11-17,городской округ Геленджик,44.589560,38.399690,189.506496,NaN,NaN,NaN,NaN,2026-02-06 10:37:47.684766
4,track0.gpx,2025-11-17,городской округ Геленджик,44.590050,38.399120,188.224640,NaN,NaN,NaN,NaN,2026-02-06 10:37:47.684766
...,...,...,...,...,...,...,...,...,...,...,...
30942,track8.gpx,2006-11-26,городской округ Новороссийск,44.736280,37.772490,0.610000,NaN,NaN,NaN,NaN,2026-02-06 10:37:47.684766
30943,track8.gpx,2006-11-26,городской округ Новороссийск,44.736330,37.771890,43.920000,NaN,NaN,NaN,NaN,2026-02-06 10:37:47.684766
30944,track8.gpx,2006-11-26,городской округ Новороссийск,44.736140,37.773240,5.420000,NaN,NaN,NaN,NaN,2026-02-06 10:37:47.684766
30945,track8.gpx,2006-11-26,городской округ Новороссийск,44.736260,37.771970,5.420000,NaN,NaN,NaN,NaN,2026-02-06 10:37:47.684766
30946,track8.gpx,2006-11-26,городской округ Новороссийск,44.736240,37.771920,-0.330000,NaN,NaN,NaN,NaN,2026-02-06 10:37:47.684766

In [3]:
df = df.rename(str, axis=1)

In [4]:
malt = df.altitude.max()
msf = df.step_frequency.max()

In [5]:
df["water_danger"] = df.apply(lambda x: (3 < x["temperature"] < 10) * 3 + (x["temperature"] >= 10) + x["water_source"] * 4 + (x["terrain_type"] == 3) * 6 + round((malt - x["altitude"])/malt, 2), axis=1)

KeyError: 'water_source'

In [ ]:
df["fire_danger"] = df.apply(lambda x: (1-x["water_source"])*2 - (x["terrain_type"] == 3) * 4 + (x["terrain_type"] == 0) * 2 + (x["terrain_type"] == 1) * 2 + round(x["temperature"]/10, 2), axis=1)

In [ ]:
mealt = (df.altitude.max() - df.altitude.min()) / 2

In [ ]:
msf = df.step_frequency.max()

In [ ]:
df["difficult"] = df.apply(lambda x: (x["terrain_type"] == 0) * 2 + (x["mountain_peak"]) * 4 + round(abs(mealt-x["altitude"])/mealt*2, 2) + (x["mountain_peak"]) * 4 + round((msf-x["step_frequency"])/msf, 2), axis=1)

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
with open("encodings.pkl", "rb") as f:
    encodings = pickle.load(f)

In [ ]:
def pca2(df):
    # Масштабирую данные
    ddf = StandardScaler().fit_transform(df)

    # Нормализирую данные
    ddt = Normalizer().fit_transform(ddf)
    
    # Уменьшаем размерность при помощи метода главных компонент
    pca = PCA(n_components=2).fit(ddt)
    pca_2d = pca.transform(ddt)
    return pca_2d

def elbow(pca_2d):
    sse = []
    # Смотрю, какая сумма квадратов расстояния для разного кол-ва класстеров
    for k in range(1, 11):
        kmeans = KMeans(n_clusters=k, random_state=42)
        kmeans.fit(pca_2d)
        sse.append(kmeans.inertia_)
    # Изображаю график метода Локтя
    plt.plot(range(1, 11), sse, marker='o')
    plt.title('Метод „Локтя“')
    plt.xlabel('Количество кластеров')
    plt.ylabel('Сумма квадратов расстояний')
    plt.show()

list_of_color = ["red", "blue", "green", "orange"]

def KMN(df, pca_2d, n_clusters):
    # Обучаю и предсказываю кластеры по уже известному их кол-ву
    km = KMeans(n_clusters=n_clusters, random_state=0, init = 'k-means++')
    all_pred = km.fit_predict(pca_2d)
    # Визуализирую кластеры
    for k in range(n_clusters):
        plt.scatter(pca_2d[all_pred==k].T[0] , pca_2d[all_pred==k].T[1], color=list_of_color[k])
        
    plt.title(f'Кластеризация KMeans')
    plt.show()

    # Описываю характеристики по каждому столбцу каждого кластера
    for i in range(n_clusters):
        print(f"{i+1} кластер. Кол-во: {km.labels_[km.labels_==i].size}\n")
        print(f"Цвет: {list_of_color[i]}\n")
        for j in df.columns:
            if j in ["bridge", "building", "mountain_peak", "none", "road", "water_source"]:
                print(f"Кол-во {j}: {df[j][km.labels_==i].sum()}")
                continue
            if j in ["region", "terrain_type"]:
                dmode = map(str, df[j][km.labels_==i].value_counts().reset_index()[j][:2])
                print(f"Преобладает {j}: {' и '.join(dmode)}")
                continue
            print(f"Среднее {j}: {df[j][km.labels_==i].mean():.3f}")
        print()
    # Применяю метрику оценки
    dbs = davies_bouldin_score(pca_2d, km.labels_) 
    print(f"Метрика кластеризации (индекс Дэвиса-Булдина): {dbs}")

### Опасная кластеризация

In [ ]:
df_for_danger = df.drop(["track_point_id", "day", "time", "longitude", "latitude", "track_id", "none", "road", "building", "bridge", "difficult"], axis=1)

In [ ]:
danger_df = pca2(df_for_danger)

,analysis_date,region,latitude,longitude,altitude,step_frequency,temperature,terrain_type,key_objects
0,2025-11-18 07:02:44.239,городской округ Геленджик,44.64188,38.002640,120.534016,231.388217,16.274265,NaN,NaN
1,2025-11-18 07:02:44.239,городской округ Геленджик,44.64188,38.002642,120.538518,231.388217,16.300000,NaN,NaN
2,2025-11-18 07:02:44.239,городской округ Геленджик,44.64335,38.003930,143.773920,231.388217,16.222794,NaN,NaN
3,2025-11-18 07:02:44.239,городской округ Геленджик,44.64382,38.004530,150.808992,231.388217,16.197059,NaN,NaN
4,2025-11-18 07:02:44.239,городской округ Геленджик,44.64410,38.005220,158.462400,231.388217,16.171324,NaN,NaN
...,...,...,...,...,...,...,...,...,...
30942,2006-11-26 16:46:24.000,городской округ Новороссийск,44.73628,37.772490,0.610000,596.515925,12.082266,NaN,NaN
30943,2006-11-26 16:52:06.000,городской округ Новороссийск,44.73633,37.771890,43.920000,596.515925,12.086700,NaN,NaN
30944,2006-11-26 17:00:39.000,городской округ Новороссийск,44.73614,37.773240,5.420000,596.515925,12.091133,NaN,NaN
30945,2006-11-26 17:06:20.000,городской округ Новороссийск,44.73626,37.771970,5.420000,596.515925,12.095567,NaN,NaN
30946,2006-11-26 17:09:46.000,городской округ Новороссийск,44.73624,37.771920,-0.330000,596.515925,12.100000,NaN,NaN

### Сложная кластеризация

In [ ]:
df_for_difficult = df.drop(["track_point_id", "day",  "longitude", "latitude", "track_id", "none", "road", "building", "bridge", "fire_danger", "water_danger", "region", "water_source", "danger_level"], axis=1)

In [ ]:
difficult_df = pca2(df_for_difficult)

In [ ]:
elbow(difficult_df)

In [ ]:
clusters_d = KMN(df_for_difficult, difficult_df, n_clusters=4)

Первый кластер - Самый легко эвакуируемый. Сложность = 1

Второй кластер - Тоже легко эвакуируемый, но есть леса. Сложность = 2

Третий кластер - Вероятно сложность возникает из-за окружения пиками. Сложность = 4

Четвёртый кластер - Находится повыше предыдущего. Это в основном луга. Сложность = 3

In [ ]:
transform_d = {0:1, 1:2, 2:4, 3:3}

In [ ]:
df["difficult_level"] = list(map(lambda x: transform_d[x], clusters_d))

In [ ]:
plt.figure(figsize=(15,10))
sns.heatmap(df.corr(), annot=True)
plt.show()

In [ ]:
df.drop(["water_danger", "fire_danger", "difficult"], axis=1, inplace=True)

In [ ]:
df.to_sql("better_data", conn, if_exists="replace")