In [ ]:
import pandas as pd
import psycopg2
import sys
import os
import numpy as np
import shap
import seaborn as sns
import matplotlib.pyplot as plt
import pickle

from random import randint, uniform
from gpx_converter import Converter
from datetime import datetime
from scipy import stats
from scipy.stats import norm
from PIL import ImageEnhance, Image

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, Normalizer
from sklearn.cluster import KMeans
from sklearn.inspection import permutation_importance
from sklearn.metrics import r2_score, davies_bouldin_score
from sklearn.decomposition import PCA

/home/user/Документы/champ/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
def connection():
     return psycopg2.connect(
        database="db_arthur", 
        user="arthur", 
        password="146a",
        host="localhost",
        port=5430)

In [4]:
connect = connection()
cursor = connect.cursor()

In [12]:
df = pd.read_sql_table(table_name="track_analysis", con="postgresql://arthur:146a@localhost:5430/db_arthur", schema="public", parse_dates=["analysis_date"])

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30947 entries, 0 to 30946
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              30947 non-null  int64
 1   track_id        30947 non-null  str
 2   analysis_date   30947 non-null  datetime64[us]
 3   region          30947 non-null  str
 4   latitude        30947 non-null  float64
 5   longitude       30947 non-null  float64
 6   altitude        25273 non-null  float64
 7   step_frequency  30947 non-null  float64
 8   temperature     30947 non-null  float64
 9   terrain_type    30947 non-null  str
 10  key_objects     30823 non-null  str
 11  created_at      30947 non-null  datetime64[us]
dtypes: datetime64[us](2), float64(5), int64(1), str(4)
memory usage: 2.8 MB

In [ ]:
def pca2(df):
    # Масштабирую данные
    ddf = StandardScaler().fit_transform(df)

    # Нормализирую данные
    ddt = Normalizer().fit_transform(ddf)
    
    # Уменьшаем размерность при помощи метода главных компонент
    pca = PCA(n_components=2).fit(ddt)
    pca_2d = pca.transform(ddt)
    return pca_2d

def elbow(pca_2d):
    sse = []
    # Смотрю, какая сумма квадратов расстояния для разного кол-ва класстеров
    for k in range(1, 11):
        kmeans = KMeans(n_clusters=k, random_state=42)
        kmeans.fit(pca_2d)
        sse.append(kmeans.inertia_)
    # Изображаю график метода Локтя
    plt.plot(range(1, 11), sse, marker='o')
    plt.title('Метод „Локтя“')
    plt.xlabel('Количество кластеров')
    plt.ylabel('Сумма квадратов расстояний')
    plt.show()

list_of_color = ["red", "blue", "green", "orange"]

def KMN(df, pca_2d, n_clusters):
    # Обучаю и предсказываю кластеры по уже известному их кол-ву
    km = KMeans(n_clusters=n_clusters, random_state=0, init = 'k-means++')
    all_pred = km.fit_predict(pca_2d)
    # Визуализирую кластеры
    for k in range(n_clusters):
        plt.scatter(pca_2d[all_pred==k].T[0] , pca_2d[all_pred==k].T[1], color=list_of_color[k])
        
    plt.title(f'Кластеризация KMeans')
    plt.show()

    # Описываю характеристики по каждому столбцу каждого кластера
    for i in range(n_clusters):
        print(f"{i+1} кластер. Кол-во: {km.labels_[km.labels_==i].size}\n")
        print(f"Цвет: {list_of_color[i]}\n")
        for j in df.columns:
            if j in ["bridge", "building", "mountain_peak", "none", "road", "water_source"]:
                print(f"Кол-во {j}: {df[j][km.labels_==i].sum()}")
                continue
            if j in ["region", "terrain_type"]:
                dmode = map(str, df[j][km.labels_==i].value_counts().reset_index()[j][:2])
                print(f"Преобладает {j}: {' и '.join(dmode)}")
                continue
            print(f"Среднее {j}: {df[j][km.labels_==i].mean():.3f}")
        print()
    # Применяю метрику оценки
    dbs = davies_bouldin_score(pca_2d, km.labels_) 
    print(f"Метрика кластеризации (индекс Дэвиса-Булдина): {dbs}")

In [46]:
df_for_pca = df.drop("track_id", axis=1)

In [47]:
df_for_pca

,id,analysis_date,region,latitude,longitude,altitude,step_frequency,temperature,terrain_type,key_objects,created_at
0,30770,2026-01-29,Бахчисарайский район,44.525137,33.917670,844.54,160.182824,10.345833,meadow,Mountain: Сандык-Кая; River: Сандык-Су; River:...,2026-01-29 06:39:51.302286
1,30784,2026-01-29,Бахчисарайский район,44.525258,33.912210,846.37,160.182824,10.404167,meadow,Mountain: Сандык-Кая; River: Сандык-Су; River:...,2026-01-29 06:39:51.302286
2,30782,2026-01-29,Бахчисарайский район,44.525290,33.912748,843.32,160.182824,10.395833,meadow,Mountain: Сандык-Кая; River: Сандык-Су; River:...,2026-01-29 06:39:51.302286
3,30783,2026-01-29,Бахчисарайский район,44.525317,33.912437,846.07,160.182824,10.400000,meadow,Mountain: Сандык-Кая; River: Сандык-Су; River:...,2026-01-29 06:39:51.302286
4,30781,2026-01-29,Бахчисарайский район,44.525328,33.913028,844.24,160.182824,10.391667,meadow,Mountain: Сандык-Кая; River: Сандык-Су; River:...,2026-01-29 06:39:51.302286
...,...,...,...,...,...,...,...,...,...,...,...
30942,31228,2026-01-29,городской округ Новороссийск,44.893570,37.481360,17.93,596.515925,11.959606,industrial,River: Котлама,2026-01-29 06:39:51.302286
30943,31229,2026-01-29,городской округ Новороссийск,44.893850,37.480060,16.50,596.515925,11.964039,industrial,River: Котлама,2026-01-29 06:39:51.302286
30944,31230,2026-01-29,городской округ Новороссийск,44.894110,37.478820,15.52,596.515925,11.968473,industrial,River: Котлама,2026-01-29 06:39:51.302286
30945,31249,2026-01-29,городской округ Новороссийск,44.894200,37.459640,11.19,596.515925,12.052709,industrial,River: Котлама,2026-01-29 06:39:51.302286
30946,31231,2026-01-29,городской округ Новороссийск,44.894390,37.477600,14.57,596.515925,11.972906,industrial,River: Котлама,2026-01-29 06:39:51.302286

In [50]:
df_for_pca['region']

0                Бахчисарайский район
1                Бахчисарайский район
2                Бахчисарайский район
3                Бахчисарайский район
4                Бахчисарайский район
                     ...
30942    городской округ Новороссийск
30943    городской округ Новороссийск
30944    городской округ Новороссийск
30945    городской округ Новороссийск
30946    городской округ Новороссийск
Name: region, Length: 30947, dtype: str

In [ ]:
df_for_pca['analysis_date'] = pd.to_numeric(pd.to_datetime(df_for_pca['analysis_date']))

In [77]:
le = LabelEncoder()
df_for_pca['region'] = le.fit_transform(df_for_pca['region'])
df_for_pca['terrain_type'] = le.fit_transform(df_for_pca['terrain_type'])
df_for_pca['key_objects'] = le.fit_transform(df_for_pca['key_objects'])
df_for_pca['latitude'] = le.fit_transform(df_for_pca['latitude'])
df_for_pca['longitude'] = le.fit_transform(df_for_pca['longitude'])
df_for_pca['altitude'] = le.fit_transform(df_for_pca['altitude'])
df_for_pca['step_frequency'] = le.fit_transform(df_for_pca['step_frequency'])
df_for_pca['temperature'] = le.fit_transform(df_for_pca['temperature'])
df_for_pca.drop(columns=["created_at", "id"])

,analysis_date,region,latitude,longitude,altitude,step_frequency,temperature,terrain_type,key_objects
0,1769644800000000,0,23757,583,2028,3,27505,4,2
1,1769644800000000,0,23759,549,2036,3,27526,4,2
2,1769644800000000,0,23760,553,2023,3,27523,4,2
3,1769644800000000,0,23761,551,2034,3,27524,4,2
4,1769644800000000,0,23762,556,2027,3,27522,4,2
...,...,...,...,...,...,...,...,...,...
30942,1769644800000000,4,26845,1153,93,7,28319,3,6
30943,1769644800000000,4,26846,1150,88,7,28322,3,6
30944,1769644800000000,4,26847,1148,86,7,28326,3,6
30945,1769644800000000,4,26848,1085,63,7,28397,3,6
30946,1769644800000000,4,26849,1146,82,7,28330,3,6

In [78]:
df_for_pca.info()

<class 'pandas.DataFrame'>
RangeIndex: 30947 entries, 0 to 30946
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              30947 non-null  int64
 1   analysis_date   30947 non-null  int64
 2   region          30947 non-null  int64
 3   latitude        30947 non-null  int64
 4   longitude       30947 non-null  int64
 5   altitude        30947 non-null  int64
 6   step_frequency  30947 non-null  int64
 7   temperature     30947 non-null  int64
 8   terrain_type    30947 non-null  int64
 9   key_objects     30947 non-null  int64
 10  created_at      30947 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(10)
memory usage: 2.6 MB

In [79]:
pca_df = pca2(df_for_pca)

DTypePromotionError: The DType <class 'numpy.dtypes.DateTime64DType'> could not be promoted by <class 'numpy.dtypes.Int64DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.DateTime64DType'>)

In [23]:
elbow(pca_df)

NameError: name 'pca_df' is not defined